[pytest]
pythonpath = .
addopts =
    --verbose
    --cov=pages
    --cov-report=term-missing
    --cov-report=html
    --cov-report=xml:coverage.xml
    --cov-fail-under=65
    --tracing retain-on-failure
    --video retain-on-failure
    --screenshot only-on-failure